services:
  postgres:
    image: postgres:16.1-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: laravel_pg
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: app
    working_dir: /var/www
    user: "1000"
    volumes:
      - ./:/var/www

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8081:80"
    depends_on:
      - app

volumes:
  pg_data:
